version: '3.9'

services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    build:
      context: ./server
    environment:
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
